language: go
go_import_path: github.com/newrelic/go-agent

matrix:
  include:
  - go: "1.7"
    env: DIRS=v3/newrelic,v3/internal,v3/examples
  - go: "1.8"
    env: DIRS=v3/newrelic,v3/internal,v3/examples
  - go: "1.9"
    env: DIRS=v3/newrelic,v3/internal,v3/examples
  - go: "1.10"
    env: DIRS=v3/newrelic,v3/internal,v3/examples
  - go: "1.11"
    env: DIRS=v3/newrelic,v3/internal,v3/examples
  - go: "1.12"
    env: DIRS=v3/newrelic,v3/internal,v3/examples
  - go: "1.13"
    env: DIRS=v3/newrelic,v3/internal,v3/examples,v3/integrations/logcontext
  - go: "1.13"
    env: DIRS=v3/integrations/nrawssdk/v1
  - go: "1.13"
    env: DIRS=v3/integrations/nrawssdk/v2
  - go: "1.13"
    env: DIRS=v3/integrations/nrecho
  - go: "1.13"
    env:
      - DIRS=v3/integrations/nrgin/v1
      - TESTMASTER=github.com/gin-gonic/gin
  - go: "1.13"
    env: DIRS=v3/integrations/nrgorilla/v1
  - go: "1.13"
    env: DIRS=v3/integrations/nrlogrus
  - go: "1.13"
    env: DIRS=v3/integrations/nrlogxi/v1
  - go: "1.13"
    env: DIRS=v3/integrations/nrpkgerrors
  - go: "1.13"
    env:
      - DIRS=v3/integrations/nrlambda
      - TESTMASTER=github.com/aws/aws-lambda-go
  - go: "1.13"
    env: DIRS=v3/integrations/nrmysql
  - go: "1.13"
    env: DIRS=v3/integrations/nrpq
  - go: "1.13"
    env:
      - DIRS=v3/integrations/nrsqlite3
      - TESTMASTER=github.com/mattn/go-sqlite3
  - go: "1.13"
    env: DIRS=v3/integrations/nrgrpc
  # As of October 2019, errors result from go get -u github.com/micro/go-micro
  # - go: "1.13"
  #   env: DIRS=v3/integrations/nrmicro
  - go: "1.13"
    env: DIRS=v3/integrations/nrnats
  - go: "1.13"
    env: DIRS=v3/integrations/nrstan
  - go: "1.13"
    env: DIRS=v3/integrations/logcontext
  - go: "1.13"
    env: DIRS=v3/integrations/nrzap
  - go: "1.13"
    env: DIRS=v3/integrations/nrhttprouter
  - go: "1.13"
    env: DIRS=v3/integrations/nrb3
  - go: "1.13"
    env: DIRS=v3/integrations/nrmongo

# Skip the install step. Don't `go get` dependencies.
install: true

script:
  - bash build-script.sh
